import type { NextPage } from 'next'
import Head from 'next/head'
import AddTask from '../components/addTask'
import TaskList from '../components/taskList'

const Home: NextPage = () => {
	return (
		<div className="">
			<Head>
				<title>Tasks Demo</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="container mx-auto py-6">
				<AddTask />
				<TaskList />
			</div>
		</div>
	)
}

export default Home
